In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
# define the kernel
kernel_size = 2
kernel = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=kernel_size)

# set the weights of the kernel
weights = torch.FloatTensor([[[1, 2], [3, 4]]])
kernel.weight.data = weights

# print the kernel
print(kernel.weight.data)

tensor([[[1., 2.],
         [3., 4.]]])


In [14]:
x = torch.ones(1, 4, 4, dtype=torch.float32)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
import torch
import torch.nn as nn

# Define the input matrix
x = torch.FloatTensor([[1, 2, 1, 1], [3, 4, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])

# Define the kernel
kernel_size = 2
kernel = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=kernel_size, stride=1, bias=False)
weights = torch.FloatTensor([[[1, 2], [3, 4]]])
kernel.weight.data = weights

# Perform the convolution operation
output = kernel(x.view(1, 1, 4, 4))

# Print the output tensor
print(output.squeeze())


RuntimeError: expected stride to be a single integer value or a list of 1 values to match the convolution dimensions, but got stride=[1, 1]

In [32]:

import torch

# Define the kernel K and input tensor x as torch Tensors
K = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)
x = torch.tensor([[[[1., 2., 1., 1.],
                    [3., 4., 1., 1.],
                    [1., 1., 1., 1.],
                    [1., 1., 1., 1.]]]], dtype=torch.float32)

# Perform convolution using torch.nn.functional.conv2d
output = torch.nn.functional.conv2d(x, K.view(1, 1, 2, 2))

# Print the output tensor
print(output.squeeze())

x.numpy().tolist()


tensor([[30., 20., 10.],
        [18., 13., 10.],
        [10., 10., 10.]])


[[[[1.0, 2.0, 1.0, 1.0],
   [3.0, 4.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0],
   [1.0, 1.0, 1.0, 1.0]]]]