In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
mata = torch.tensor([[1,2],[3,4]])
matb = torch.ones(4,4)
matb[0:2,0:2] = mata
print("matb",matb)
def convolvemanual(mata,matb,stride):
    hor = mata.shape[1]
    ver = mata.shape[0]
    hor_end = matb.shape[0]
    ver_end = matb.shape[1]

    output = torch.zeros(ver_end-(ver-1)-(stride-1),hor_end-(hor-1)-(stride-1))
    for i in range(0,ver_end-(ver-1),stride):
        for j in range(0,hor_end-(hor-1),stride):
            patch = matb[i:i+ver,j:j+hor]
            out_elem = (patch * mata)
            output[int(i/stride),int(j/stride)] = out_elem.sum()
            print("patch is:\n",patch)
            print("\nresult of multiplying by mask:\n",out_elem)
            print("\nsum of these values:\n",out_elem.sum().item(),"\n")            
    return output

convolvemanual(mata,matb,2)

matb tensor([[1., 2., 1., 1.],
        [3., 4., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
patch is:
 tensor([[1., 2.],
        [3., 4.]])

result of multiplying by mask:
 tensor([[ 1.,  4.],
        [ 9., 16.]])

sum of these values:
 30.0 

patch is:
 tensor([[1., 1.],
        [1., 1.]])

result of multiplying by mask:
 tensor([[1., 2.],
        [3., 4.]])

sum of these values:
 10.0 

patch is:
 tensor([[1., 1.],
        [1., 1.]])

result of multiplying by mask:
 tensor([[1., 2.],
        [3., 4.]])

sum of these values:
 10.0 

patch is:
 tensor([[1., 1.],
        [1., 1.]])

result of multiplying by mask:
 tensor([[1., 2.],
        [3., 4.]])

sum of these values:
 10.0 



tensor([[30., 10.],
        [10., 10.]])

In [3]:
# Define the kernel K and input tensor x as torch Tensors
K = torch.tensor([[1, 1], 
                  [1, 1]], dtype=torch.float32)
x = torch.tensor([[[[1., 2., 3., 4.],
                    [5., 6., 7., 8.],
                    [9., 10., 11., 12.],
                    [13., 14., 15., 16.]]]], dtype=torch.float32)

# Perform convolution using torch.nn.functional.conv2d

output = torch.nn.functional.conv2d(x, K.view(1, 1, 2, 2))
# Print the output tensor
print(output.squeeze())
print(output.squeeze().shape)


tensor([[14., 18., 22.],
        [30., 34., 38.],
        [46., 50., 54.]])
torch.Size([3, 3])


In [63]:
K = torch.tensor([[[1, 2], 
                   [3, 4]],
                  
                  [[5, 6], 
                   [7, 8]]], dtype=torch.float32)

x = torch.tensor([[[[1., 2., 1., 1.],
                    [3., 4., 1., 1.],
                    [1., 1., 1., 1.],
                    [1., 1., 1., 1.]],

                   [[1., 2., 1., 1.],
                    [3., 4., 1., 1.],
                    [1., 1., 1., 1.],
                    [1., 1., 1., 1.]],

                   [[1., 2., 1., 1.],
                    [3., 4., 1., 1.],
                    [1., 1., 1., 1.],
                    [1., 1., 1., 1.]]]], dtype=torch.float32)

# Perform 3D convolution using torch.nn.functional.conv3d
output = torch.nn.functional.conv3d(x, K.view(1, 1, 2, 2, 2), stride=2)

# Print the output tensor
print(output.squeeze())
print(output.squeeze().shape)


tensor([[100.,  36.],
        [ 36.,  36.]])
torch.Size([2, 2])
